#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail

UBUNTU_DISTRO="${UBUNTU_DISTRO:-ubuntu}"
GATEWAY_PORT="${GATEWAY_PORT:-18789}"
GATEWAY_BIND="${GATEWAY_BIND:-loopback}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# 你的规则目录：如果你实际是 memory/，就把 rules 改成 memory
REPO_RULES="${REPO_ROOT}/memory"

# ---- choose droidrun provider/model in Termux, then pass to Ubuntu via temp env ----
TMP_ENV="${TMPDIR:-/data/data/com.termux/files/usr/tmp}/clawbot-env.$$.sh"
trap 'rm -f "$TMP_ENV"' EXIT

# Respect user overrides if provided
DROIDRUN_PROVIDER_CHOSEN="${DROIDRUN_PROVIDER:-}"
DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL:-}"

pick_llm_termux() {
  # 0) user override (provider+model both set)
  if [ -n "${DROIDRUN_PROVIDER_CHOSEN}" ] && [ -n "${DROIDRUN_MODEL_CHOSEN}" ]; then
    return 0
  fi

  # 1) order: Gemini -> OpenAI -> Anthropic -> DeepSeek -> Ollama(local)
  if [ -n "${GEMINI_API_KEY:-}" ]; then
    DROIDRUN_PROVIDER_CHOSEN="Gemini"
    DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL_CHOSEN:-gemini-2.5-flash}"
    return 0
  fi

  if [ -n "${OPENAI_API_KEY:-}" ]; then
    DROIDRUN_PROVIDER_CHOSEN="OpenAI"
    DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL_CHOSEN:-gpt-5.2}"
    return 0
  fi

  if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
    DROIDRUN_PROVIDER_CHOSEN="Anthropic"
    DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL_CHOSEN:-claude-3-5-sonnet-latest}"
    return 0
  fi

  if [ -n "${DEEPSEEK_API_KEY:-}" ]; then
    DROIDRUN_PROVIDER_CHOSEN="DeepSeek"
    DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL_CHOSEN:-deepseek-chat}"
    return 0
  fi

  # Ollama: only choose if user explicitly wants it (since Termux may not have ollama)
  if [ -n "${DROIDRUN_PROVIDER_CHOSEN}" ] && [ -z "${DROIDRUN_MODEL_CHOSEN}" ]; then
    return 0
  fi

  return 1
}

if pick_llm_termux; then
  echo "[run] picked droidrun llm in termux: provider=${DROIDRUN_PROVIDER_CHOSEN} model=${DROIDRUN_MODEL_CHOSEN}"
else
  echo "[run] WARNING: no LLM key found in Termux env. Set one of GEMINI_API_KEY/OPENAI_API_KEY/ANTHROPIC_API_KEY/DEEPSEEK_API_KEY."
fi

# Write ONLY chosen provider/model (and the necessary API key) into TMP_ENV
{
  echo "# generated by run.sh"

  if [ -n "${DROIDRUN_PROVIDER_CHOSEN:-}" ] && [ -n "${DROIDRUN_MODEL_CHOSEN:-}" ]; then
    printf "export DROIDRUN_PROVIDER=%q\n" "${DROIDRUN_PROVIDER_CHOSEN}"
    printf "export DROIDRUN_MODEL=%q\n" "${DROIDRUN_MODEL_CHOSEN}"
  fi

  # write only the key needed for the chosen provider
  case "${DROIDRUN_PROVIDER_CHOSEN:-}" in
    Gemini)
      [ -n "${GEMINI_API_KEY:-}" ] && printf "export GEMINI_API_KEY=%q\n" "$GEMINI_API_KEY"
      ;;
    OpenAI)
      [ -n "${OPENAI_API_KEY:-}" ] && printf "export OPENAI_API_KEY=%q\n" "$OPENAI_API_KEY"
      ;;
    Anthropic)
      [ -n "${ANTHROPIC_API_KEY:-}" ] && printf "export ANTHROPIC_API_KEY=%q\n" "$ANTHROPIC_API_KEY"
      ;;
    DeepSeek)
      [ -n "${DEEPSEEK_API_KEY:-}" ] && printf "export DEEPSEEK_API_KEY=%q\n" "$DEEPSEEK_API_KEY"
      ;;
  esac
} > "$TMP_ENV"

echo "[clawbot] Starting OpenClaw Gateway..."
proot-distro login "${UBUNTU_DISTRO}" --shared-tmp -- bash -lc "
  set -euo pipefail

  REPO_ROOT='${REPO_ROOT}'
  REPO_RULES='${REPO_RULES}'

  # ---- import chosen droidrun provider/model (and required key) from Termux ----
  if [ -f '${TMP_ENV}' ]; then
    source '${TMP_ENV}'
  fi

  echo \"[run] droidrun chosen: provider=\${DROIDRUN_PROVIDER:-<empty>} model=\${DROIDRUN_MODEL:-<empty>}\" 
  echo \"[run] key check: OPENAI_API_KEY=\${OPENAI_API_KEY:+<set>} GEMINI_API_KEY=\${GEMINI_API_KEY:+<set>} ANTHROPIC_API_KEY=\${ANTHROPIC_API_KEY:+<set>} DEEPSEEK_API_KEY=\${DEEPSEEK_API_KEY:+<set>}\

  cd \"\$REPO_ROOT\"

  # ---- ensure env.sh patch also loads (node netif patch) ----
  if [ -f installer/ubuntu/env.sh ]; then
    source installer/ubuntu/env.sh
  fi

  # ---- activate python virtual environment ----
  # 推荐：不要只 activate, 还要显式指定 CLAW_MOBILE_PYTHON, 避免 openclaw worker PATH 重置
  if [ -f \"/root/venvs/clawbot/bin/activate\" ]; then
    source \"/root/venvs/clawbot/bin/activate\"
    if [ -x \"/root/venvs/clawbot/bin/python3\" ]; then
      export CLAW_MOBILE_PYTHON=\"/root/venvs/clawbot/bin/python3\"
    else
      export CLAW_MOBILE_PYTHON=\"/root/venvs/clawbot/bin/python\"
    fi
  else
    echo \"[run] WARNING: venv not found at /root/venvs/clawbot; tools may use system python\"
  fi

  echo \"[run] CLAW_MOBILE_PYTHON=\${CLAW_MOBILE_PYTHON:-}\" || true

  # ---- configure external rules for memory_search (read-only) ----
  if [ -d \"\$REPO_RULES\" ]; then
    openclaw config set agents.defaults.memorySearch.extraPaths \"[\\\"\$REPO_RULES\\\"]\" >/dev/null 2>&1 || true
    echo \"[run] memorySearch.extraPaths set to: \$REPO_RULES\"
  else
    echo \"[run] rules folder not found at \$REPO_RULES (ok)\"
  fi

  exec openclaw gateway --bind ${GATEWAY_BIND} --port ${GATEWAY_PORT} --verbose
"