#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail

UBUNTU_DISTRO="${UBUNTU_DISTRO:-ubuntu}"
GATEWAY_PORT="${GATEWAY_PORT:-18789}"
GATEWAY_BIND="${GATEWAY_BIND:-loopback}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
REPO_RULES="${REPO_ROOT}/memory"
PLUGIN_DIR="${REPO_ROOT}/openclaw-plugin-mobile-ui"

# ---- choose droidrun provider/model in Termux, then pass to Ubuntu via temp env ----
TMP_ENV="${TMPDIR:-/data/data/com.termux/files/usr/tmp}/clawbot-env.$$.sh"
trap 'rm -f "$TMP_ENV"' EXIT

DROIDRUN_PROVIDER_CHOSEN="${DROIDRUN_PROVIDER:-}"
DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL:-}"

pick_llm_termux() {
  # user override wins
  if [ -n "${DROIDRUN_PROVIDER_CHOSEN}" ] && [ -n "${DROIDRUN_MODEL_CHOSEN}" ]; then
    return 0
  fi

  # order: Gemini -> OpenAI -> Anthropic -> DeepSeek (Ollama handled in Ubuntu if needed)
  if [ -n "${GEMINI_API_KEY:-}" ]; then
    DROIDRUN_PROVIDER_CHOSEN="Gemini"
    DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL_CHOSEN:-gemini-2.5-flash}"
    return 0
  fi

  if [ -n "${OPENAI_API_KEY:-}" ]; then
    DROIDRUN_PROVIDER_CHOSEN="OpenAI"
    DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL_CHOSEN:-gpt-4o-mini}"
    return 0
  fi

  if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
    DROIDRUN_PROVIDER_CHOSEN="Anthropic"
    DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL_CHOSEN:-claude-3-5-sonnet-latest}"
    return 0
  fi

  if [ -n "${DEEPSEEK_API_KEY:-}" ]; then
    DROIDRUN_PROVIDER_CHOSEN="DeepSeek"
    DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL_CHOSEN:-deepseek-chat}"
    return 0
  fi

  return 1
}

if pick_llm_termux; then
  echo "[run] picked droidrun llm in termux: provider=${DROIDRUN_PROVIDER_CHOSEN} model=${DROIDRUN_MODEL_CHOSEN}"
else
  echo "[run] WARNING: no LLM key found in Termux env. Set one of GEMINI_API_KEY/OPENAI_API_KEY/ANTHROPIC_API_KEY/DEEPSEEK_API_KEY."
fi

# Write ONLY chosen provider/model + the one required API key to TMP_ENV
{
  echo "# generated by run.sh"

  if [ -n "${DROIDRUN_PROVIDER_CHOSEN:-}" ] && [ -n "${DROIDRUN_MODEL_CHOSEN:-}" ]; then
    printf "export DROIDRUN_PROVIDER=%q\n" "${DROIDRUN_PROVIDER_CHOSEN}"
    printf "export DROIDRUN_MODEL=%q\n" "${DROIDRUN_MODEL_CHOSEN}"
  fi

  case "${DROIDRUN_PROVIDER_CHOSEN:-}" in
    Gemini)    [ -n "${GEMINI_API_KEY:-}" ] && printf "export GEMINI_API_KEY=%q\n" "$GEMINI_API_KEY" ;;
    OpenAI)    [ -n "${OPENAI_API_KEY:-}" ] && printf "export OPENAI_API_KEY=%q\n" "$OPENAI_API_KEY" ;;
    Anthropic) [ -n "${ANTHROPIC_API_KEY:-}" ] && printf "export ANTHROPIC_API_KEY=%q\n" "$ANTHROPIC_API_KEY" ;;
    DeepSeek)  [ -n "${DEEPSEEK_API_KEY:-}" ] && printf "export DEEPSEEK_API_KEY=%q\n" "$DEEPSEEK_API_KEY" ;;
  esac
} > "$TMP_ENV"

echo "[clawbot] Starting OpenClaw Gateway..."
proot-distro login "${UBUNTU_DISTRO}" --shared-tmp -- bash -lc "
  set -euo pipefail

  REPO_ROOT='${REPO_ROOT}'
  REPO_RULES='${REPO_RULES}'
  PLUGIN_DIR='${PLUGIN_DIR}'
  TMP_ENV='${TMP_ENV}'

  # ---- import chosen droidrun provider/model + key ----
  if [ -f \"\$TMP_ENV\" ]; then
    source \"\$TMP_ENV\"
  fi

  echo \"[run] droidrun chosen: provider=\${DROIDRUN_PROVIDER:-<empty>} model=\${DROIDRUN_MODEL:-<empty>}\"
  echo \"[run] key check: OPENAI_API_KEY=\${OPENAI_API_KEY:+<set>} GEMINI_API_KEY=\${GEMINI_API_KEY:+<set>} ANTHROPIC_API_KEY=\${ANTHROPIC_API_KEY:+<set>} DEEPSEEK_API_KEY=\${DEEPSEEK_API_KEY:+<set>}\"

  cd \"\$REPO_ROOT\"

  # ---- ensure env.sh patch also loads (node netif patch) ----
  if [ -f installer/ubuntu/env.sh ]; then
    source installer/ubuntu/env.sh
  fi

  # ---- activate python virtual environment + pin CLAW_MOBILE_PYTHON ----
  if [ -f \"/root/venvs/clawbot/bin/activate\" ]; then
    source \"/root/venvs/clawbot/bin/activate\"
    if [ -x \"/root/venvs/clawbot/bin/python3\" ]; then
      export CLAW_MOBILE_PYTHON=\"/root/venvs/clawbot/bin/python3\"
    else
      export CLAW_MOBILE_PYTHON=\"/root/venvs/clawbot/bin/python\"
    fi
  else
    echo \"[run] WARNING: venv not found at /root/venvs/clawbot; tools may use system python\"
  fi
  echo \"[run] CLAW_MOBILE_PYTHON=\${CLAW_MOBILE_PYTHON:-}\" || true

  # ---- ADB prep: pick a usable device serial automatically ----
  if command -v adb >/dev/null 2>&1; then
    adb start-server >/dev/null 2>&1 || true
    mapfile -t DEVICES < <(adb devices | awk 'NR>1 && \$2==\"device\" {print \$1}')
    if [ \${#DEVICES[@]} -eq 0 ]; then
      echo \"[run] WARNING: no adb device in 'device' state.\"
      echo \"[run] adb devices output:\"
      adb devices || true
      echo \"[run] If unauthorized: enable USB/Wireless debugging and accept prompt on phone.\"
    else
      if [ -z \"\${DROIDRUN_SERIAL:-}\" ]; then
        export DROIDRUN_SERIAL=\"\${DEVICES[0]}\"
      fi
      echo \"[run] adb selected serial: \${DROIDRUN_SERIAL}\"
    fi
  else
    echo \"[run] WARNING: adb not found.\"
  fi

  # ---- build plugin if needed, then plugins install ----
  if [ -d \"\$PLUGIN_DIR\" ]; then
    if [ ! -d \"\$PLUGIN_DIR/dist\" ]; then
      echo \"[run] building plugin (dist missing)...\"
      cd \"\$PLUGIN_DIR\"
      npm i -D @types/node
      npm install
      npm run build
      cd \"\$REPO_ROOT\"
    fi

    echo \"[run] openclaw plugins install \$PLUGIN_DIR\"
    openclaw plugins install \"\$PLUGIN_DIR\" || true
  else
    echo \"[run] WARNING: plugin dir not found at \$PLUGIN_DIR\"
  fi

  # ---- configure external rules for memory_search (read-only) ----
  if [ -d \"\$REPO_RULES\" ]; then
    JSON_RULES=\$(printf '[\"%s\"]' \"\$REPO_RULES\")
    openclaw config set agents.defaults.memorySearch.extraPaths \"\$JSON_RULES\" >/dev/null 2>&1 || true
    echo \"[run] memorySearch.extraPaths set to: \$REPO_RULES\"
  else
    echo \"[run] rules folder not found at \$REPO_RULES (ok)\"
  fi

  exec openclaw gateway --bind ${GATEWAY_BIND} --port ${GATEWAY_PORT} --verbose
"